# Generated by Django 5.2.4 on 2025-07-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='NomeNaoInformado', max_length=100, unique=True),
        ),
    ]
